### ISSUE TITLE
Move to robotology-legacy 

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/codyco-legacy#1]
I noticed that we have a https://github.com/robotology-legacy organization, I think that this repo fits well there, what do you think @drdanz @pattacini  ?

**Comment by pattacini** [comment]
Indeed :+1:

**Comment by pattacini** [comment]
Do you wanna me move it there?

**Comment by traversaro** [comment]
It would be ideal, thanks!

**Comment by pattacini** [comment]
Done :smile:
